# arquivo: .github/workflows/jest.yml

name: Teste Jest

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Instalar dependências
        run: npm install

      - name: Executar testes
        run: npm test
